//! End-to-end simulation helpers for HFT-style engine testing.
//!
//! This module is meant to answer "does the engine behave under sustained
//! synthetic market pressure?" without requiring real exchange connectivity.
//!
//! # What it simulates
//! - bursty command ingestion via bounded SPSC ring buffers
//! - mixed command types (`New`, `Cancel`, `Replace`)
//! - partitioned routing and draining
//! - event production volume and rough throughput estimates
//!
//! # What it does **not** simulate
//! - real market-data protocol semantics
//! - network jitter/packet loss at socket level
//! - queue-position effects from an external venue
//!
//! # Typical usage
//! ```text
//! let cfg = SimulationConfig::default();
//! let report = run_partitioned_simulation(cfg);
//! println!("{report:?}");
//! ```

use std::sync::Arc;
use std::thread;
use std::time::Instant;

use crate::command::{EngineCommand, IdempotencyKey, OrderCommand};
use crate::partition::PartitionRuntime;
use crate::types::{OrderId, OrderType, Side, TimeInForce};

/// Tunables for synthetic engine simulation.
#[derive(Clone, Debug)]
pub struct SimulationConfig {
    /// Number of engine partitions.
    pub partitions: usize,
    /// Queue capacity per partition (must be power of two).
    pub ingress_capacity_per_partition: usize,
    /// Number of producer threads generating commands.
    pub producers: usize,
    /// Number of commands generated by each producer.
    pub commands_per_producer: u64,
    /// Base price used by synthetic price generator.
    pub base_price_ticks: u64,
    /// Number of price ticks around base price used for random walk.
    pub price_band_ticks: u64,
    /// Every Nth command attempts a cancel (if local state has an order).
    pub cancel_every: u64,
    /// Every Nth command attempts a replace (if local state has an order).
    pub replace_every: u64,
}

impl Default for SimulationConfig {
    fn default() -> Self {
        Self {
            partitions: 4,
            ingress_capacity_per_partition: 16_384,
            producers: 2,
            commands_per_producer: 50_000,
            base_price_ticks: 10_000,
            price_band_ticks: 32,
            cancel_every: 17,
            replace_every: 29,
        }
    }
}

/// Aggregate simulation result.
#[derive(Clone, Debug, Default)]
pub struct SimulationReport {
    /// Total generated commands.
    pub commands_generated: u64,
    /// Commands successfully enqueued.
    pub commands_enqueued: u64,
    /// Commands dropped due to full queue.
    pub commands_dropped: u64,
    /// Total emitted execution events.
    pub events_emitted: u64,
    /// End-to-end wall time in milliseconds.
    pub elapsed_ms: u128,
    /// Approximate command throughput (`commands_enqueued / elapsed_sec`).
    pub commands_per_sec: f64,
    /// Approximate event throughput (`events_emitted / elapsed_sec`).
    pub events_per_sec: f64,
}

#[derive(Clone, Debug)]
struct ProducerStats {
    generated: u64,
    enqueued: u64,
    dropped: u64,
}

/// Small deterministic pseudo-random generator (LCG).
///
/// We avoid external RNG dependencies to keep this crate minimal and deterministic.
#[derive(Clone, Copy, Debug)]
struct Lcg(u64);

impl Lcg {
    fn new(seed: u64) -> Self {
        Self(seed)
    }

    fn next_u64(&mut self) -> u64 {
        // Constants from Numerical Recipes style LCG; sufficient for synthetic load shaping.
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0
    }
}

/// Runs a partitioned simulation with concurrent producers and returns summary metrics.
pub fn run_partitioned_simulation(cfg: SimulationConfig) -> SimulationReport {
    assert!(cfg.producers > 0, "producers must be > 0");
    assert!(cfg.partitions > 0, "partitions must be > 0");
    assert!(cfg.price_band_ticks > 0, "price_band_ticks must be > 0");

    let runtime = Arc::new(PartitionRuntime::new(
        cfg.partitions,
        cfg.ingress_capacity_per_partition,
    ));

    let started_at = Instant::now();
    let mut handles = Vec::with_capacity(cfg.producers);

    for producer_idx in 0..cfg.producers {
        let rt = Arc::clone(&runtime);
        let local_cfg = cfg.clone();
        handles.push(thread::spawn(move || produce_commands(producer_idx as u64, &local_cfg, &rt)));
    }

    // Aggregate producer stats after all generators finish.
    let mut generated = 0_u64;
    let mut enqueued = 0_u64;
    let mut dropped = 0_u64;
    for handle in handles {
        let stats = handle.join().expect("producer thread failed");
        generated = generated.wrapping_add(stats.generated);
        enqueued = enqueued.wrapping_add(stats.enqueued);
        dropped = dropped.wrapping_add(stats.dropped);
    }

    // Drain all partition queues once producers are done.
    let events = runtime.drain_all();
    let elapsed = started_at.elapsed();
    let elapsed_ms = elapsed.as_millis();
    let elapsed_sec = elapsed.as_secs_f64().max(1e-9);

    SimulationReport {
        commands_generated: generated,
        commands_enqueued: enqueued,
        commands_dropped: dropped,
        events_emitted: events.len() as u64,
        elapsed_ms,
        commands_per_sec: enqueued as f64 / elapsed_sec,
        events_per_sec: events.len() as f64 / elapsed_sec,
    }
}

fn produce_commands(seed: u64, cfg: &SimulationConfig, runtime: &PartitionRuntime) -> ProducerStats {
    let mut rng = Lcg::new(seed ^ 0x9E3779B97F4A7C15);
    // Local list of live-ish order ids used to generate cancel/replace pressure.
    let mut local_orders: Vec<OrderId> = Vec::with_capacity(2048);

    let mut generated = 0_u64;
    let mut enqueued = 0_u64;
    let mut dropped = 0_u64;

    for i in 0..cfg.commands_per_producer {
        generated = generated.wrapping_add(1);
        let order_id = OrderId(((seed as u128) << 48 | i as u128) as u64);
        let idem = IdempotencyKey(((seed as u128) << 64) | i as u128);

        let cmd = if i > 0 && i % cfg.replace_every == 0 && !local_orders.is_empty() {
            let idx = (rng.next_u64() as usize) % local_orders.len();
            let target = local_orders[idx];
            let new_order = build_new_order_command(idem, order_id, &mut rng, cfg);
            EngineCommand::Replace {
                idempotency_key: idem,
                cancel_order_id: target,
                new_order,
            }
        } else if i > 0 && i % cfg.cancel_every == 0 && !local_orders.is_empty() {
            let idx = (rng.next_u64() as usize) % local_orders.len();
            let target = local_orders[idx];
            EngineCommand::Cancel {
                idempotency_key: idem,
                order_id: target,
            }
        } else {
            local_orders.push(order_id);
            EngineCommand::New(build_new_order_command(idem, order_id, &mut rng, cfg))
        };

        if runtime.enqueue(cmd).is_ok() {
            enqueued = enqueued.wrapping_add(1);
        } else {
            // Queue full is expected in stress runs. We count but continue.
            dropped = dropped.wrapping_add(1);
        }
    }

    ProducerStats {
        generated,
        enqueued,
        dropped,
    }
}

fn build_new_order_command(
    idempotency_key: IdempotencyKey,
    order_id: OrderId,
    rng: &mut Lcg,
    cfg: &SimulationConfig,
) -> OrderCommand {
    let side = if rng.next_u64() & 1 == 0 {
        Side::Buy
    } else {
        Side::Sell
    };
    let price_offset = rng.next_u64() % (cfg.price_band_ticks * 2);
    let price_ticks = cfg.base_price_ticks + price_offset.saturating_sub(cfg.price_band_ticks);
    let quantity = 1 + (rng.next_u64() % 20);

    OrderCommand {
        idempotency_key,
        order_id,
        side,
        order_type: OrderType::Limit,
        tif: TimeInForce::Gtc,
        price_ticks,
        quantity,
    }
}

#[cfg(test)]
mod tests {
    use super::{run_partitioned_simulation, SimulationConfig};

    #[test]
    fn simulation_smoke_test() {
        let cfg = SimulationConfig {
            partitions: 2,
            ingress_capacity_per_partition: 2048,
            producers: 1,
            commands_per_producer: 5_000,
            base_price_ticks: 10_000,
            price_band_ticks: 16,
            cancel_every: 11,
            replace_every: 19,
        };

        let report = run_partitioned_simulation(cfg);
        assert!(report.commands_generated > 0);
        assert_eq!(
            report.commands_generated,
            report.commands_enqueued + report.commands_dropped
        );
    }
}
